import { StoreNav } from '@/components/ui/_Store/StoreNav/StoreNav'
import { Footer } from '@/components/views/MainPage/Footer/Footer'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../customStyles.css'
import '../globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Old Sailor Barber',
  description: 'Generated by create next app',
}

export default function StoreLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} min-h-dvh h-full flex flex-col justify-between w-full text-neutral-300 selection:bg-primary bg-neutral-800 selection:text-neutral-800`}
      >
        <StoreNav />
        <main className="flex flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  )
}
