import { CartProvider } from '@/components/ui/_Store/CartProvider/CartProvider'
import { AOSProvider } from '@/components/ui/AOS/AOSProvider/AOSProvider'
import { AOSWrapper } from '@/components/ui/AOS/AOSWrapper/AOSWrapper'
import { Footer } from '@/components/ui/Footer/Footer'
import { Navigation } from '@/components/views/Store/Navigation/Navigation'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from 'react-hot-toast'
import '../customStyles.css'
import '../globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Old Sailor Barber',
  description: 'Generated by create next app',
}

export default function StoreLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} min-h-dvh h-full flex flex-col justify-between w-full text-neutral-300 selection:bg-primary bg-neutral-800 selection:text-neutral-800`}
      >
        <Toaster position="bottom-center" reverseOrder={false} />
        <CartProvider>
          <AOSProvider>
            <AOSWrapper className="flex flex-col flex-1">
              <Navigation />
              <main className="flex flex-1">{children}</main>
              <Footer />
            </AOSWrapper>
          </AOSProvider>
        </CartProvider>
      </body>
    </html>
  )
}
